[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PATH = "/opt/build/repo/netlify/bin:/opt/buildhome/node-deps/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[dev]
  publish = "public"
  port = 8889

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
